GET http://localhost:3010/banners
Accept: application/json

###

GET http://localhost:3010/downloads
Accept: application/json

###
GET http://localhost:3010/products?offset=10
Accept: application/json
###
GET http://localhost:3010/products?category=vassoura&offset=0
Accept: application/json
###
GET http://localhost:3010/categories
Accept: application/json