GET http://localhost:3010/banners
Accept: application/json

###

GET http://localhost:3010/downloads
Accept: application/json

###
GET http://localhost:3010/products?offset=0
Accept: application/json
###
GET http://localhost:3010/products?category=categorie_name&offset=0
Accept: application/json
###
GET http://localhost:3010/categories
Accept: application/json
###

GET http://localhost:3010/categories?url=linha-domestica/rodos
Accept: application/json

###
GET http://localhost:3010/products/vassoura-bellinha
Accept: application/json

###
GET http://localhost:3010/products?search=vassoura
Accept: application/json